title: "Enrique Goberna — Blog"
description: "Dark minimalist blog about building my portfolio"
url: "https://enriquegoberna.com"
baseurl: ""
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
minimal_mistakes_skin: "custom"
paginate: 10
paginate_path: "/blog/page:num"
permalink: /blog/:title/
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      related: true
exclude:
  - node_modules
  - vendor
  - Gemfile.lock
  - "*.zip"
